# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-11 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BbsReply',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('istop', models.IntegerField(blank=True, null=True)),
                ('isdel', models.SmallIntegerField(blank=True, null=True)),
                ('isblock', models.SmallIntegerField(blank=True, null=True)),
                ('createtime', models.DateTimeField(blank=True, null=True)),
                ('isdisable', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bbs_reply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=60)),
                ('parentid', models.IntegerField()),
                ('compere', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('orderby', models.IntegerField(blank=True, null=True)),
                ('namestyle', models.CharField(blank=True, max_length=10, null=True)),
                ('logo', models.CharField(blank=True, max_length=200, null=True)),
                ('themenum', models.IntegerField(blank=True, null=True)),
                ('replynum', models.IntegerField(blank=True, null=True)),
                ('lastpost', models.CharField(blank=True, max_length=600, null=True)),
            ],
            options={
                'db_table': 'bbs_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Friendlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.CharField(blank=True, max_length=300, null=True)),
                ('orderby', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'bbs_friendlink',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lockip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bbs_lockip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField()),
                ('paytime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bbs_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('content', models.TextField(blank=True, null=True)),
                ('replies', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('istop', models.IntegerField()),
                ('iselite', models.IntegerField()),
                ('ishot', models.IntegerField()),
                ('price', models.IntegerField()),
                ('isdel', models.SmallIntegerField()),
                ('publishtime', models.DateTimeField(blank=True, null=True)),
                ('isdisadle', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bbs_posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Siteinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
                ('isclose', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bbs_siteinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('portrait', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('usertype', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('autologin', models.IntegerField(blank=True, null=True)),
                ('regtime', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bbs_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('qq', models.CharField(blank=True, max_length=15, null=True)),
                ('signature', models.CharField(blank=True, max_length=200, null=True)),
                ('quesstion', models.CharField(blank=True, max_length=100, null=True)),
                ('answer', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'bbs_userdetail',
                'managed': False,
            },
        ),
    ]
