# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-12 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Third_app',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=True, verbose_name='删除标记')),
                ('app_id', models.CharField(max_length=64, verbose_name='应用AppID')),
                ('app_secret', models.CharField(max_length=64, verbose_name='应用App密钥')),
                ('app_description', models.CharField(max_length=100, verbose_name='应用App描述')),
            ],
            options={
                'verbose_name': '应用App',
                'verbose_name_plural': '应用App',
                'db_table': 'third_app',
            },
        ),
    ]
