# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-17 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': False},
        ),
    ]
