# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-12 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=True, verbose_name='删除标记')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总价格')),
                ('total_count', models.IntegerField(verbose_name='订单商品总数量')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('order_status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '待发货'), (3, '待收货'), (4, '待评价'), (5, '已完成')], default=1, verbose_name='订单状态')),
                ('snap_img', models.ImageField(upload_to='snap_img', verbose_name='订单快照图片')),
                ('sanp_name', models.CharField(max_length=32, verbose_name='订单快照名称')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
                'db_table': 'order',
            },
        ),
    ]
